In [2]:
from quantum_newton_raphson import newton_raphson
from scipy.sparse import csc_matrix
import numpy as np

array([[ 2,  0,  4],
       [ 0,  0,  5],
       [ 4,  5, 12]])

In [45]:
def func(input):
    def f1(x,y,z):
        return 2*x**3 - x*y + 4*z - 12
    def f2(x,y,z):
        return -4*x + z**5 + 8*z*y
    def f3(x,y,z):
        return 3*x*3 + z**5 + 8*z*y
    x, y, z = input
    return np.array([f(x,y,z) for f in[f1,f2,f3]])

def grad(input):
    def df1(x,y,z):
        return np.array([6*x**2 - y, -x, 4]) 
    def df2(x,y,z):
        return np.array([-4, 8*z, 5*z**4])
    def df3(x,y,z):
        return np.array([9*x**2, 8*z, 5*z**4 + 8*y])
    out = np.zeros((3,3))
    x,y,z = input
    out[0,:] = df1(x,y,z)
    out[1,:] = df2(x,y,z)
    out[2,:] = df3(x,y,z)

    return out

In [68]:
def finite_difference_grads(input, func, eps=1e-6):
    size = input.shape[0]
    out = np.zeros((size,size))

    for ix in range(size):
        input_temp = np.copy(input)
        input_temp[ix] += eps
        grad_ix = func(input_temp)
        input_temp[ix] -= 2*eps
        grad_ix -= func(input_temp)

        out[:, ix] = grad_ix / eps / 2
    return out 

In [69]:
x = np.random.rand(3)
f = func(x)
f

array([-10.6828362 ,  -3.44384324,   9.46835155])

In [70]:
g = grad(x)
g

array([[ 4.98664394e+00, -9.93245752e-01,  4.00000000e+00],
       [-4.00000000e+00,  5.67392242e-01,  1.26515469e-04],
       [ 8.87883412e+00,  5.67392242e-01,  7.46075697e+00]])

In [71]:
gx = finite_difference_grads(x, func, eps=1E-12)
gx

0 [0.99324575 0.93257881 0.07092403]
1 [0.99324575 0.93257881 0.07092403]
2 [0.99324575 0.93257881 0.07092403]


array([[ 4.98623365, -0.99298347,  4.0003556 ],
       [-3.99991151,  0.56754601,  7.46092077],
       [ 8.99991193,  0.56754601,  7.46069873]])

In [50]:
gx

array([[ 3.85864933,  0.98967834, 13.98967834],
       [ 3.85597177,  0.99767834, 13.99767834],
       [ 3.85697177,  0.99888102, 13.99888102]])