In [ ]:
import scipy.sparse
from scipy.sparse import sparray, triu
import numpy as np 

In [ ]:
A = scipy.sparse.random(5,5, density = 0.5, format='csr')
A = A + A.T
A.todense()

matrix([[1.33054254, 0.37713158, 0.        , 0.87937383, 0.4372376 ],
        [0.37713158, 0.        , 0.81785691, 0.27187483, 1.01724692],
        [0.        , 0.81785691, 0.        , 0.        , 0.        ],
        [0.87937383, 0.27187483, 0.        , 0.        , 1.49414634],
        [0.4372376 , 1.01724692, 0.        , 1.49414634, 0.        ]])

In [ ]:
Abool = (scipy.sparse.triu(A, k=1) != 0)
Abool.sum(1).flatten()

matrix([[3, 3, 0, 1, 0]])

In [ ]:
np.argsort(Abool.sum(1).flatten())

matrix([[2, 4, 3, 0, 1]])

In [ ]:
np.argsort(Abool.sum(1).flatten())

matrix([[2, 4, 3, 0, 1]])

In [ ]:
from quantum_newton_raphson.splu_solve import splu_solve, get_ordering

In [ ]:
b = scipy.sparse.random(5,1, density = 0.5, format='csr')

In [ ]:
idx = get_ordering(A, 'max_edge', {})

In [ ]:
A[np.ix_(idx,idx)]

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 15 stored elements in Compressed Sparse Row format>

In [ ]:
b  = np.random.rand(5,1)
b = b[idx]

In [ ]:
from scipy.sparse.linalg import splu 
solver = splu(A, permc_spec="NATURAL")

/home/nico/miniconda3/envs/alliander_powerflow/lib/python3.9/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py:412: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


In [ ]:
solver.solve(b)

array([[-0.61005325],
       [ 0.3619184 ],
       [-0.61640271],
       [ 0.59032058],
       [ 0.8077424 ]])

In [ ]:
splu_solve(A,b )

UnboundLocalError: local variable 'splu' referenced before assignment