In [1]:
import scipy.sparse
from scipy.sparse import sparray, triu
import numpy as np 

In [2]:
A = scipy.sparse.random(5,5, density = 0.5, format='csr')
A = A + A.T
A.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.49103631],
        [0.        , 0.53125312, 0.        , 0.33615756, 0.40046539],
        [0.        , 0.        , 1.66212745, 1.81558723, 1.93320869],
        [0.        , 0.33615756, 1.81558723, 0.84050777, 0.        ],
        [0.49103631, 0.40046539, 1.93320869, 0.        , 0.58033689]])

In [3]:
Abool = (scipy.sparse.triu(A, k=1) != 0)
Abool.sum(1).flatten()

matrix([[1, 2, 2, 0, 0]])

In [4]:
np.argsort(Abool.sum(1).flatten())

matrix([[3, 4, 0, 1, 2]])

In [5]:
np.argsort(Abool.sum(1).flatten())

matrix([[3, 4, 0, 1, 2]])

In [6]:
from quantum_newton_raphson.splu_solve import splu_solve, get_ordering

In [7]:
b = scipy.sparse.random(5,1, density = 0.5, format='csr')

In [8]:
idx = get_ordering(A, 'max_edge', {})

In [9]:
A[np.ix_(idx,idx)]

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [14]:
b  = np.random.rand(5)
b = b[idx]

In [15]:
from scipy.sparse.linalg import splu 
solver = splu(A, permc_spec="NATURAL")

In [16]:
solver.solve(b)

array([-5.44455012,  1.80075399,  0.90861376, -1.83942444,  1.02078255])

In [18]:
res = splu_solve(A,b )

In [19]:
A.dot(res.solution)

array([0.50124129, 0.74710782, 0.14398206, 0.70895406, 0.39660565])

In [20]:
b

array([0.50124129, 0.74710782, 0.14398206, 0.70895406, 0.39660565])

In [22]:
x = {'reorder':3}
a = x.pop('reorder')
x

{}

In [25]:
options = {'reorder':'max_edge'}
reorder_method = options.pop('reorder') if "reorder" in options else "max_edge"

In [26]:
options

{'reorder': 'max_edge'}

In [30]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [31]:
reordering_functions = {
    "max_edge": 1,
    "quantum": 2,
    "no_reordering": 3,
}

In [33]:
"Ordering method not recognized, valid options are {}".format(
    list(reordering_functions.keys()))

"Ordering method not recognized, valid options are ['max_edge', 'quantum', 'no_reordering']"